image:
  file: .gitpod.Dockerfile

ports:
  - port: 25565
    onOpen: notify

vscode:
  extensions:
    - richardwillis.vscode-gradle
    - vscode-icons-team.vscode-icons
    - esbenp.prettier-vscode
    - vscjava.vscode-java-pack

tasks:
  - name: build
    command: ./gradlew build